CTRL+1 no-osd change-list glsl-shaders set "~~/shaders/anime4k/Anime4K_Clamp_Highlights.glsl:~~/shaders/anime4k/Anime4K_Restore_CNN_M.glsl:~~/shaders/anime4k/Anime4K_Upscale_CNN_x2_M.glsl:~~/shaders/anime4k/Anime4K_Restore_CNN_S.glsl:~~/shaders/anime4k/Anime4K_AutoDownscalePre_x2.glsl:~~/shaders/anime4k/Anime4K_AutoDownscalePre_x4.glsl:~~/shaders/anime4k/Anime4K_Upscale_CNN_x2_S.glsl"; show-text "Anime4K"
CTRL+0 no-osd change-list glsl-shaders clr ""; show-text "GLSL shaders cleared"

# Alterna entre velocidade normal (440Hz) e o modo relaxante 432Hz puro (sem artefatos digitais)
F4 cycle-values speed 1.0 0.981818 ; cycle-values audio-pitch-correction yes no
