# Forçar o uso da decodificação de vídeo por hardware VA-API.
# Isso descarrega o trabalho da CPU para a GPU Intel.
hwdec=vaapi

# Definir a saída de vídeo para o renderizador moderno 'gpu'.
vo=gpu

# Usar o contexto nativo do Wayland para o renderizador de GPU.
# Esta é a opção mais eficiente e livre de "tearing" para o seu ambiente.
gpu-context=wayland

# Pipeline de Áudio Audiófilo e de Alta Fidelidade
ao=pipewire                 # Força a saída nativa de alta performance do PipeWire
audio-format=float          # Saída nativa em 32-bit float (bit-depth perfeito para o PipeWire/EasyEffects)
audio-channels=stereo       # Garante estéreo puro
video-sync=display-resample # Mantém áudio e vídeo perfeitamente sincronizados de forma fluida

# Configurações do SoX Resampler (soxr) apenas para transposição ativa do F4 (432Hz)
# Ao desativar o pitch correction, a reamostragem física usará precisão extrema
audio-resample-filter-size=32
audio-resample-linear=yes
