# Forçar o uso da decodificação de vídeo por hardware VA-API.
# Isso descarrega o trabalho da CPU para a GPU Intel.
hwdec=vaapi

# Definir a saída de vídeo para o renderizador moderno 'gpu'.
vo=gpu

# Usar o contexto nativo do Wayland para o renderizador de GPU.
# Esta é a opção mais eficiente e livre de "tearing" para o seu ambiente.
gpu-context=wayland
